name: benchmarks

on:
  push:
    branches: [master,abseil-unordered-map]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add focal PPA
      run: sudo add-apt-repository ppa:bleedingedge/focal-bleed && sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install -y libbenchmark-dev libbenchmark-tools python3-scipy libabsl-dev
    - name: Make
      run: make
    - name: Test
      run: make test
